const theme = {
  colors: {
    background: '#fff',
    navBackground: 'rgba(255, 255, 255, 0.2)',
    navItem: '#fff',
    navHover: '#777',
    navSocials: 'rgba(0, 0, 0, 0.2)',
    whiteNavItem: '#999',
    whiteNavItemHover: '#000',
    mobileMenuBackground: '#fff',
    mobileListBackground: '#222',
    mobileListText: '#fff',
    moblieListItemBackground: '#333',
    introText: '#fff',
    introTextBackground: 'rgba(0, 0, 0, 0.2);',
    introHr: '#999',
    introButton: '#fff',
    introButtonTextHover: '#333',
    text: '#555',
    title: '#111',
    titleBackground: '#fafafa',
    aboutCard: '#999',
    aboutCardActive: '#333',
    aboutCardText: '#353535',
    aboutCardHr: 'rgb(194, 194, 194)',
    aboutCarouselTitleBackground: '#E4E3E5',
    aboutCarouselButton: '#dfdfdf',
    aboutCarouselIcon: '#111',
    aboutCarouselHoverIcon: '#fff',
    aboutCarouselIconOut: '#214cce',
    slideshowBackground: '#ddd',
    carouselButton: '#dfdfdf',
    carouselButtonHover: '#000',
    carouselHr: '#ddd',
    carouselHrHover: '#333',
    carouselHrActive: '#aaa',
    exampleBackground: '#222222',
    exampleHover: 'rgba(0, 0, 0, 0.8)',
    serviceCard: 'rgba(0,0,0,0.06)',
    serviceCardBackground: '#fff',
    serviceCardShadow: '#2c3e50',
    testimonialText: '#fff',
    testimonialEmployee: '#eee',
    testimonialRole: 'rgba(255,255,255,0.60)',
    companyDot: 'rgba(255,255,255,0.60)',
    companyDotActive: '#ecf0f1',
    memberTitle: '#353535',
    memberTitleBackground: '#E4E3E5',
    memberSocials: '#fff',
    memberSocialsBackground: 'rgba(0, 0, 0, 0.2)',
    contactHr: '#999',
    contactText: '#fff',
    contactButtonTextHover: '#333',
    footerBackground: '#1b1b1b',
    footerText: '#fff',
    footerSocialsBackground: 'rgba(0, 0, 0, 0.2)',
    backTop: '#1b1b1b',
    twitter: '#4CC2FF',
    facebook: '#3B5998',
    googlePlus: '#D23E2B'
  }
}

export default theme
